all:
	javac -cp /home/lili/workspace/github-code/mycode/java/practise:/home/lili/workspace/dev-lib/java-dev-lib/commons-logging-1.2.jar:/home/lili/workspace/dev-lib/java-dev-lib/commons-pool2-2.4.1.jar:/home/lili/workspace/dev-lib/java-dev-lib/commons-dbcp2-2.1.jar:/usr/share/java/mysql.jar dss/demo/MainFrame.java
test:
	java -cp /home/lili/workspace/github-code/mycode/java/practise:/home/lili/workspace/dev-lib/java-dev-lib/commons-logging-1.2.jar:/home/lili/workspace/dev-lib/java-dev-lib/commons-pool2-2.4.1.jar:/home/lili/workspace/dev-lib/java-dev-lib/commons-dbcp2-2.1.jar:/usr/share/java/mysql.jar dss.demo.MainFrame
